theme = "terminal"
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishdir = "../build"
author = "Tom Whitwell"
title = "Tom Whitwell"
pluralizelisttitles = false
paginate = 5

# Theme Parameters
[params]
contentTypeName = "blog"
themeColor = "blue"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false

[languages]

[languages.en]
languageName = "English"
title = "Tom Whitwell"
subtitle = "A simple, retro theme for Hugo"
owner = "Tom Whitwell"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "Tom Whitwell"
logoHomeLink = "/"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "certs"
name = "Certifications"
url = "/certs"
